services:
  django:
    container_name: django
    build:
      context: ./Django/
      dockerfile: Dockerfile
    # env_file:
    #   - .env
    ports:
      - "8000:8000"
    restart: unless-stopped
    volumes:
      - django:/CineFast
    networks:
      - Cinefast
  nginx:
    container_name: nginx
    build:
      context: ./Nginx
      dockerfile: Dockerfile
    ports:
      - "8443:8443"
    restart: unless-stopped
    networks:
      - Cinefast
    depends_on:
      - django


volumes:
  django:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: data/django

networks:
  Cinefast:
    driver: bridge